export interface book {
  title: string;
  author: string;
  desc: string;
  year: string;
  filename: string;
  imagename: string;
  group: string;
}

export const bookscards: book[] = [
  {
    title: "Competitive programming handbook",
    author: "Antti Laaksonen",
    desc: "El propósito de este libro es darte una introducción completa a la programación competitiva. Se asume que ya dominas lo básico de programación, pero no es necesario que poseas conocimientos previos de programación competitiva.",
    year: "2020",
    filename: "(Español) Competitive Programmer’s Handbook.pdf",
    imagename: "1.jpg",
    group: "Fundamentos de competitiva",
  },
  {
    title: "Guía de programación en Java",
    author: "Julian Stiven Muñetones",
    desc: "Guía de nivel básico para el aprendizaje de la sintaxis básica de java, con toques de enfoque en programación competitiva",
    year: "2021",
    filename: "Intro java.pdf",
    imagename: "2.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Guia de programación en C++",
    author: "Edwin Villarraga",
    desc: "Guía de nivel básico para el aprendizaje de la sintaxis básica de C++, con toques de enfoque en programación competitiva",
    year: "2021",
    filename: "intro cpp.pdf",
    imagename: "3.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Guia de programación en Python",
    author: "Daniel Alayon",
    desc: "Guía de nivel básico para el aprendizaje de la sintaxis básica de Python, con toques de enfoque en programación competitiva",
    year: "2021",
    filename: "intro py.pdf",
    imagename: "4.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Discrete Structures (ingles)",
    author: "Rob Hoogerwoord & Hans Zantema",
    desc: "Documento explicativo en ingles sobre los las distintas operaciones matematicas pertenecientes a la matematica discreta, nivel intermedio - avanzado",
    year: "2016",
    filename: "Matematica discreta.pdf",
    imagename: "5.jpg",
    group: "Matemáticas",
  },
  {
    title: "Matemática discreta",
    author: "Francesc Comellas - Josep Fàbrega - Anna Sànchez - Oriol Serra",
    desc: "Documento explicativo sobre los las distintas operaciones matematicas pertenecientes a la matematica discreta, nivel intermedio - avanzado",
    year: "2001",
    filename: "matemtica_discreta_para_informticos.pdf",
    imagename: "6.jpg",
    group: "Matemáticas",
  },
  {
    title: "Principles of Algorithmic Problem Solving (ingles)",
    author: "Johan Sannemo",
    desc: "La resolución algorítmica de problemas es el arte de formular métodos eficientes que resolver problemas de carácter matemático.",
    year: "2018",
    filename: "Principles of Algorithmic Problem Solving.pdf",
    imagename: "7.jpg",
    group: "Matemáticas",
  },
  {
    title: "Advanced Data Structure (ingles)",
    author: "Geek4Geeks",
    desc: "Documento recopilatorio de algoritmos para estructuras de datos avanzadas o especializadas.",
    year: "2022",
    filename: "Advanced-Data-Structure.pdf",
    imagename: "8.jpg",
    group: "Estructuras de datos",
  },
  {
    title: "Algorithms (ingles)",
    author: "Notes For Professionals",
    desc: "Libro introductorio (nivel básico) de algoritmia para iniciados",
    year: "2022",
    filename: "AlgorithmsNotesForProfessionals.pdf",
    imagename: "9.jpg",
    group: "Algorítmica",
  },
  {
    title: "Algoritmos voraces",
    author: "Aprende olimpiadas informaticas",
    desc: "Pequeño libro teorico acerca de las ideas base de los algoritmos voraces (Básico).",
    year: "2022",
    filename: "Algoritmos Voraces.pdf",
    imagename: "10.jpg",
    group: "Algorítmica",
  },
  {
    title: "Arrays (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en Arrays (Básico a experto).",
    year: "2022",
    filename: "Arrays.pdf",
    imagename: "11.jpg",
    group: "Estructuras de datos",
  },
  {
    title: "Backtracking (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en Backtracking y programación dinámica (Básico a experto).",
    year: "2022",
    filename: "Arrays.pdf",
    imagename: "12.jpg",
    group: "Algorítmica",
  },
  {
    title: "Binary Search Tree (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en arboles de busqueda binaria (Básico a experto).",
    year: "2022",
    filename: "Binary-Search-Tree.pdf",
    imagename: "13.jpg",
    group: "Estructuras de datos",
  },
  {
    title: "Bit Magic (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en magia binaria BitWise (Básico a experto).",
    year: "2022",
    filename: "Bit-Magic.pdf",
    imagename: "14.jpg",
    group: "Bit Wise",
  },
  {
    title: "Combinatorial (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en combinatorias y estadística (Básico a experto).",
    year: "2022",
    filename: "Combinatorial.pdf",
    imagename: "15.jpg",
    group: "Matemáticas",
  },
  {
    title: "C++ (Ingles)",
    author: "Notes For Professionals",
    desc: "Libro teórico del lenguaje C++ desde nivel básico hasta avanzado.",
    year: "2022",
    filename: "CPlusPlusNotesForProfessionals.pdf",
    imagename: "16.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Divide And Conquer (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en la metodología de resolución de problemas, divide y conquista (Básico a experto).",
    year: "2022",
    filename: "Divide-And-Conquer.pdf",
    imagename: "17.jpg",
    group: "Algorítmica",
  },
  {
    title: "Dynamic Programming (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en la metodología de resolución de problemas con programación dinámica y los algoritmos basados en DP (Básico a experto).",
    year: "2022",
    filename: "Dynamic-Programming.pdf",
    imagename: "18.jpg",
    group: "Algorítmica",
  },
  {
    title: "Pilas, Colas, Listas, Árboles y Grafos",
    author: "Universidad Autónoma del Estado de México",
    desc: "Este libro tiene por objetivo que el programador identifique las herramientas teóricas fundamentales para la representación y manipulación de información en la computadora, haciendo énfasis en el tipo de datos dinámicos con base en éste. (Básico)",
    year: "2019",
    filename: "estructuras de datos.pdf",
    imagename: "19.jpg",
    group: "Estructuras de datos",
  },
  {
    title: "Game Theory (ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en teorías de juegos (Básico a experto).",
    year: "2022",
    filename: "Game-Theory.pdf",
    imagename: "20.jpg",
    group: "Algorítmica",
  },
  {
    title: "Geometric Algorithms (ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos de geometría computacional (Básico a experto).",
    year: "2022",
    filename: "Geometric-Algorithms.pdf",
    imagename: "21.jpg",
    group: "Geometría",
  },
  {
    title: "Graphs (ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos de teoría de grafos, arboles, flujos y redes (Básico a experto).",
    year: "2022",
    filename: "Graphs.pdf",
    imagename: "22.jpg",
    group: "Grafos",
  },
  {
    title: "Greedy (ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos voraces (Básico a experto).",
    year: "2022",
    filename: "Greedy.pdf",
    imagename: "23.jpg",
    group: "Algorítmica",
  },
  {
    title: "Hashing (ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en hasheos (Básico a experto).",
    year: "2022",
    filename: "Hashing.pdf",
    imagename: "24.jpg",
    group: "Algorítmica",
  },
  {
    title: "Heaps (ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en heaps (Básico a experto).",
    year: "2022",
    filename: "Heaps.pdf",
    imagename: "25.jpg",
    group: "Algorítmica",
  },
  {
    title: "Introducción a la Algoritmia I - Eficiencia",
    author: "Aprende olimpiada informática",
    desc: "Explica aquellas propiedades de los algoritmos que están relacionadas con la cantidad de recursos utilizados por el algoritmo",
    year: "2022",
    filename: "Introducción a la Algoritmia I Eficiencia.pdf",
    imagename: "26.jpg",
    group: "Algorítmica",
  },
  {
    title: "Introducción a la Algoritmia II - Costes",
    author: "Aprende olimpiada informática",
    desc: "Demuestra ejemplos de costes al momento de ejecutar algoritmos.",
    year: "2022",
    filename: "Introducción a la Algoritmia II Costes.pdf",
    imagename: "27.jpg",
    group: "Algorítmica",
  },
  {
    title: "Introducción a la Algoritmia III - Ejemplos de análisis de costes",
    author: "Aprende olimpiada informática",
    desc: "Demuestra ejemplos de costes al momento de ejecutar algoritmos.",
    year: "2022",
    filename:
      "Introducción a la Algoritmia III Ejemplos de análisis de costes.pdf",
    imagename: "28.jpg",
    group: "Algorítmica",
  },
  {
    title: "Introducción a la Algoritmia IV - Coste de ordenar",
    author: "Aprende olimpiada informática",
    desc: "Demuestra ejemplos de costes al momento de ejecutar algoritmos.",
    year: "2022",
    filename: "Introducción a la Algoritmia IV Coste de ordenar.pdf",
    imagename: "29.jpg",
    group: "Algorítmica",
  },
  {
    title: "Java (Ingles)",
    author: "Notes For Professionals",
    desc: "Libro teórico del lenguaje C++ desde nivel básico hasta avanzado.",
    year: "2022",
    filename: "JavaNotesForProfessionals.pdf",
    imagename: "30.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Linked List (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en listas enlazadas y listas doblemente enlazadas (Básico a experto).",
    year: "2022",
    filename: "Linked-List.pdf",
    imagename: "31.jpg",
    group: "Estructuras de datos",
  },
  {
    title: "Discrete Structures (Ingles)",
    author: "Rob Hoogerwoord y Hans Zantema",
    desc: "Libro de dificultad intermedia acerca de matemática discreta",
    year: "2016",
    filename: "Matematica discreta.pdf",
    imagename: "32.jpg",
    group: "Matemáticas",
  },
  {
    title: "Matemática discreta",
    author: "Francesc Comellas - Josep Fàbrega - Anna Sànchez - Oriol Serra",
    desc: "Libro de dificultad intermedia acerca de matemática discreta",
    year: "2001",
    filename: "matemtica_discreta_para_informticos.pdf",
    imagename: "33.jpg",
    group: "Matemáticas",
  },
  {
    title: "Principles of Algorithmic Problem Solving (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en matrices de diferentes dimensiones (Básico a experto).",
    year: "2022",
    filename: "Matrix.pdf",
    imagename: "34.jpg",
    group: "Estructuras de datos",
  },
  {
    title: "Programación Dinámica I - Fundamentos",
    author: "Aprende olimpiada informática",
    desc: "Pequeño libro introductorio a la programación dinámica, adecuado para principiantes",
    year: "2022",
    filename: "Programación Dinámica I Fundamentos.pdf",
    imagename: "35.jpg",
    group: "Algorítmica",
  },
  {
    title: "Programación Dinámica II - Ejemplos más avanzados",
    author: "Aprende olimpiada informática",
    desc: "Pequeño libro introductorio a la programación dinámica, adecuado para principiantes",
    year: "2022",
    filename: "Programación Dinámica II Ejemplos más avanzados.pdf",
    imagename: "36.jpg",
    group: "Algorítmica",
  },
  {
    title: "Python (Ingles)",
    author: "Notes For Professionals",
    desc: "Libro teórico del lenguaje Python desde nivel básico hasta avanzado.",
    year: "2022",
    filename: "PythonNotesForProfessionals.pdf",
    imagename: "37.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Recursion (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos basados en el método de resolución de problemas, recursividad (Básico a experto).",
    year: "2022",
    filename: "Recursion.pdf",
    imagename: "38.jpg",
    group: "Algorítmica",
  },
  {
    title: "Recursividad",
    author: "Aprende Olimpiada Informática",
    desc: "Pequeño libro introductorio a los algoritmos recursivos, adecuado para principiantes",
    year: "2022",
    filename: "Recursividad.pdf",
    imagename: "39.jpg",
    group: "Algorítmica",
  },
  {
    title: "Ruby (Ingles)",
    author: "Notes For Professionals",
    desc: "Libro teórico del lenguaje Ruby desde nivel básico hasta avanzado.",
    year: "2022",
    filename: "RubyNotesForProfessionals.pdf",
    imagename: "40.jpg",
    group: "Lenguajes de programación",
  },
  {
    title: "Searching (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos de búsquedas de todo tipo (Básico a experto).",
    year: "2022",
    filename: "Searching.pdf",
    imagename: "41.jpg",
    group: "Algorítmica",
  },
  {
    title: "Sorting (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos de ordenamiento de todo tipo de datos (Básico a experto).",
    year: "2022",
    filename: "Sorting.pdf",
    imagename: "42.jpg",
    group: "Algorítmica",
  },
  {
    title: "Strings (Ingles)",
    author: "Geeks4Geeks",
    desc: "Documento recopilatorio de algoritmos de matching y manipulación de Strings (Básico a experto).",
    year: "2022",
    filename: "Strings.pdf",
    imagename: "43.jpg",
    group: "Algorítmica",
  },
];
